# Generated by Django 2.0.7 on 2018-07-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winesite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WineTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine_id', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('winery', models.TextField(blank=True, null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('province', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('varietal', models.TextField(blank=True, null=True)),
                ('vintage', models.TextField(blank=True, null=True)),
                ('style', models.TextField(blank=True, null=True)),
                ('wine_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wine-table',
                'managed': False,
            },
        ),
    ]
